### ISSUE TITLE
Implement Dendrogram + Leaf purity measures for DeepECT

### ISSUE THREAD

**Issue by roebbert92** [julianSchilcher/LMU_Master_Practical_SoSe24#22]
My understanding from the supplied code:
1. They construct a tree with nodes containing the indices of the dataset as assignments

We need to: 
1. output from the predict method a clustering tree containing the indices of the dataset as assignments

**Comment by jian7star** [comment]
yes

**Comment by roebbert92** [comment]
Can you then please point me to where your code is? Because all I see that you just copied the code from the paper...

**Comment by jian7star** [comment]
I upload the deepect with the dendrogram and leaf purity measurement as "deepect_with_hierachical".
